### ISSUE TITLE
Photos Are Out of Order

### ISSUE THREAD

**Issue by ajheisler** [zhxie/projects-dance#2]
I am unable to fix the correct order of the photos. If you look at each individual item, the photos are all out of order. When I go in to edit the photos and reorder them, the photos are listed numerically in the correct order. But the item page does not reflect that.

**Comment by zhxie** [comment]
fixed via https://github.com/zhxie/edancemarket-prod/commit/05935806246b9cf470a5ece8173bc6360cf32dc5
